/**
 * ptBrAutocorrect.ts
 * Dicionário de autocorreção de acentos para Português Brasileiro.
 * Aplica substituições case-insensitive preservando a capitalização original.
 *
 * Estratégia: corresponde palavras inteiras (word-boundary) para evitar
 * falsos positivos. Ex: "nao" → "não", mas "naom" permanece intacto.
 */

// Mapa: forma SEM acento → forma COM acento correta
const DICT: Record<string, string> = {
  // ── ARTIGOS / PREPOSIÇÕES / CONJUNÇÕES ─────────────────────────────────────
  nao: 'não',
  ja: 'já',
  apos: 'após',
  alem: 'além',
  ate: 'até',
  atraves: 'através',
  tambem: 'também',
  porem: 'porém',
  entao: 'então',
  pois: 'pois',
  para: 'para',
  ainda: 'ainda',
  mesmo: 'mesmo',
  propria: 'própria',
  proprias: 'próprias',
  proprio: 'próprio',
  proprios: 'próprios',
  unico: 'único',
  unica: 'única',
  unicos: 'únicos',
  unicas: 'únicas',
  varios: 'vários',
  varias: 'várias',
  otimo: 'ótimo',
  otima: 'ótima',
  otimos: 'ótimos',
  otimas: 'ótimas',
  rapido: 'rápido',
  rapida: 'rápida',
  rapidos: 'rápidos',
  rapidas: 'rápidas',
  facil: 'fácil',
  faceis: 'fáceis',
  dificil: 'difícil',
  dificeis: 'difíceis',
  util: 'útil',
  uteis: 'úteis',
  agil: 'ágil',
  ageis: 'ágeis',
  acoes: 'ações',
  acao: 'ação',
  solucao: 'solução',
  solucoes: 'soluções',
  funcao: 'função',
  funcoes: 'funções',
  opcao: 'opção',
  opcoes: 'opções',
  secao: 'seção',
  secoes: 'seções',
  versao: 'versão',
  versoes: 'versões',
  conexao: 'conexão',
  conexoes: 'conexões',
  integracao: 'integração',
  integracoes: 'integrações',
  configuracao: 'configuração',
  configuracoes: 'configurações',
  instalacao: 'instalação',
  instalacoes: 'instalações',
  operacao: 'operação',
  operacoes: 'operações',
  implementacao: 'implementação',
  manutencao: 'manutenção',
  autenticacao: 'autenticação',
  autorizacao: 'autorização',
  otimizacao: 'otimização',
  comunicacao: 'comunicação',
  criacao: 'criação',
  geracao: 'geração',
  migracao: 'migração',
  documentacao: 'documentação',
  sincronizacao: 'sincronização',
  notificacao: 'notificação',
  validacao: 'validação',
  excecao: 'exceção',
  excecoes: 'exceções',
  emissao: 'emissão',
  emissoes: 'emissões',
  transmissao: 'transmissão',
  sessao: 'sessão',
  sessoes: 'sessões',
  permissao: 'permissão',
  permissoes: 'permissões',
  conclusao: 'conclusão',
  inclusao: 'inclusão',
  exclusao: 'exclusão',
  reducao: 'redução',
  producao: 'produção',
  conducao: 'condução',
  aplicacao: 'aplicação',
  relacao: 'relação',
  relacoes: 'relações',
  situacao: 'situação',
  situacoes: 'situações',
  evolucao: 'evolução',
  resolucao: 'resolução',
  descricao: 'descrição',
  descricoes: 'descrições',
  atencao: 'atenção',
  atencoes: 'atenções',
  gestao: 'gestão',
  protecao: 'proteção',
  atuacao: 'atuação',
  avaliacao: 'avaliação',
  aprovacao: 'aprovação',
  capacitacao: 'capacitação',
  colaboracao: 'colaboração',
  participacao: 'participação',
  publicacao: 'publicação',
  realizacao: 'realização',
  revisao: 'revisão',
  revisoes: 'revisões',
  alocacao: 'alocação',
  adaptacao: 'adaptação',
  automacao: 'automação',
  organizacao: 'organização',
  especificacao: 'especificação',
  contratacao: 'contratação',
  implantacao: 'implantação',
  administracao: 'administração',
  movimentacao: 'movimentação',
  atualizacao: 'atualização',
  declaracao: 'declaração',
  associacao: 'associação',
  modelagem: 'modelagem',

  // ── VERBOS (INFINITIVO) ────────────────────────────────────────────────────
  comecar: 'começar',
  comeco: 'começo',
  comecei: 'comecei',
  comecamos: 'começamos',
  atuei: 'atuei',
  atuar: 'atuar',
  atuo: 'atuo',
  desenvolver: 'desenvolver',
  desenvolvi: 'desenvolvi',
  desenvolveu: 'desenvolveu',
  desenvolvemos: 'desenvolvemos',
  desenvolvo: 'desenvolvo',
  implementar: 'implementar',
  implementei: 'implementei',
  implementou: 'implementou',
  implementamos: 'implementamos',
  implantar: 'implantar',
  implantei: 'implantei',
  implantou: 'implantou',
  criar: 'criar',
  criei: 'criei',
  criou: 'criou',
  criamos: 'criamos',
  integrar: 'integrar',
  integrei: 'integrei',
  integrou: 'integrou',
  integramos: 'integramos',
  otimizar: 'otimizar',
  otimizei: 'otimizei',
  otimizou: 'otimizou',
  configurar: 'configurar',
  configurei: 'configurei',
  configurou: 'configurou',
  configuramos: 'configuramos',
  gerenciar: 'gerenciar',
  gerenciei: 'gerenciei',
  gerenciou: 'gerenciou',
  gerencio: 'gerencio',
  automatizar: 'automatizar',
  automatizei: 'automatizei',
  automatizou: 'automatizou',
  publicar: 'publicar',
  publiquei: 'publiquei',
  publicou: 'publicou',
  liderar: 'liderar',
  liderei: 'liderei',
  liderou: 'liderou',
  monitorar: 'monitorar',
  monitorei: 'monitorei',
  monitorou: 'monitorou',
  migrar: 'migrar',
  migrei: 'migrei',
  migrou: 'migrou',
  arquitetar: 'arquitetar',
  arquitetei: 'arquitetei',
  arquitetou: 'arquitetou',
  depurar: 'depurar',
  depurei: 'depurei',
  depurou: 'depurou',
  colaborar: 'colaborar',
  colaborei: 'colaborei',
  colaborou: 'colaborou',
  evoluir: 'evoluir',
  contribuir: 'contribuir',
  contribui: 'contribuí',
  contribuiu: 'contribuiu',
  participar: 'participar',
  participei: 'participei',
  participou: 'participou',
  treinar: 'treinar',
  treinei: 'treinei',
  treinou: 'treinou',
  projetar: 'projetar',
  projetei: 'projetei',
  projetou: 'projetou',
  entregar: 'entregar',
  entreguei: 'entreguei',
  entregou: 'entregou',
  resolver: 'resolver',
  resolvi: 'resolvi',
  resolveu: 'resolveu',
  resolvemos: 'resolvemos',
  administrar: 'administrar',
  administrei: 'administrei',
  administrou: 'administrou',
  conduzir: 'conduzir',
  conduzi: 'conduzi',
  conduziu: 'conduziu',
  produzir: 'produzir',
  produzi: 'produzi',
  produziu: 'produziu',
  reduzir: 'reduzir',
  reduzi: 'reduzi',
  reduziu: 'reduziu',
  planejar: 'planejar',
  planejei: 'planejei',
  planejou: 'planejou',
  documentar: 'documentar',
  documentei: 'documentei',
  documentou: 'documentou',
  analisar: 'analisar',
  analisei: 'analisei',
  analisou: 'analisou',
  revisar: 'revisar',
  revisei: 'revisei',
  revisou: 'revisou',
  mapear: 'mapear',
  mapeei: 'mapeei',
  mapeou: 'mapeou',
  testar: 'testar',
  testei: 'testei',
  testou: 'testou',
  validar: 'validar',
  validei: 'validei',
  validou: 'validou',
  garantir: 'garantir',
  garanti: 'garanti',
  garantiu: 'garantiu',
  suportar: 'suportar',
  suportei: 'suportei',
  suportou: 'suportou',
  padronizar: 'padronizar',
  padronizei: 'padronizei',
  padronizou: 'padronizou',
  aprimorar: 'aprimorar',
  aprimorei: 'aprimorei',
  aprimorou: 'aprimorou',
  refatorar: 'refatorar',
  refatorei: 'refatorei',
  refatorou: 'refatorou',
  conectar: 'conectar',
  conectei: 'conectei',
  conectou: 'conectou',
  persistir: 'persistir',
  persisti: 'persisti',
  persistiu: 'persistiu',
  escalar: 'escalar',
  escalei: 'escalei',
  escalou: 'escalou',
  hospedar: 'hospedar',
  hospedei: 'hospedei',
  hospedou: 'hospedou',
  adaptar: 'adaptar',
  adaptei: 'adaptei',
  adaptou: 'adaptou',
  sincronizar: 'sincronizar',
  sincronizei: 'sincronizei',
  sincronizou: 'sincronizou',
  atender: 'atender',
  atendi: 'atendi',
  atendeu: 'atendeu',
  atendemos: 'atendemos',
  proteger: 'proteger',
  protegi: 'protegi',
  protegeu: 'protegeu',
  comunicar: 'comunicar',
  comuniquei: 'comuniquei',
  comunicou: 'comunicou',
  facilitar: 'facilitar',
  facilitei: 'facilitei',
  facilitou: 'facilitou',

  // ── SUBSTANTIVOS ───────────────────────────────────────────────────────────
  analise: 'análise',
  analises: 'análises',
  logica: 'lógica',
  logicas: 'lógicas',
  logico: 'lógico',
  logicos: 'lógicos',
  tecnico: 'técnico',
  tecnica: 'técnica',
  tecnicos: 'técnicos',
  tecnicas: 'técnicas',
  sequencia: 'sequência',
  sequencias: 'sequências',
  pratica: 'prática',
  praticas: 'práticas',
  pratico: 'prático',
  praticos: 'práticos',
  automatico: 'automático',
  automatica: 'automática',
  automaticos: 'automáticos',
  automaticas: 'automáticas',
  publico: 'público',
  publica: 'pública',
  publicos: 'públicos',
  publicas: 'públicas',
  basico: 'básico',
  basica: 'básica',
  basicos: 'básicos',
  basicas: 'básicas',
  academico: 'acadêmico',
  academica: 'acadêmica',
  academicos: 'acadêmicos',
  academicas: 'acadêmicas',
  profissional: 'profissional',
  pagina: 'página',
  paginas: 'páginas',
  ingles: 'inglês',
  frances: 'francês',
  portugues: 'português',
  espanhol: 'espanhol',
  numero: 'número',
  numeros: 'números',
  codigo: 'código',
  codigos: 'códigos',
  periodo: 'período',
  periodos: 'períodos',
  modulo: 'módulo',
  modulos: 'módulos',
  indice: 'índice',
  indices: 'índices',
  metodo: 'método',
  metodos: 'métodos',
  topico: 'tópico',
  topicos: 'tópicos',
  servico: 'serviço',
  servicos: 'serviços',
  negocios: 'negócios',
  negocio: 'negócio',
  repositorio: 'repositório',
  repositorios: 'repositórios',
  historico: 'histórico',
  historicos: 'históricos',
  diagnostico: 'diagnóstico',
  diagnosticos: 'diagnósticos',
  cenario: 'cenário',
  cenarios: 'cenários',
  criterio: 'critério',
  criterios: 'critérios',
  usuario: 'usuário',
  usuarios: 'usuários',
  curriculo: 'currículo',
  curriculos: 'currículos',
  possibilidade: 'possibilidade',
  alunos: 'alunos',
  academias: 'academias',
  empresa: 'empresa',
  empresas: 'empresas',
  formacao: 'formação',
  habilidade: 'habilidade',
  habilidades: 'habilidades',
  competencia: 'competência',
  competencias: 'competências',
  experiencia: 'experiência',
  experiencias: 'experiências',
  lideranca: 'liderança',
  liderancas: 'lideranças',
  treinamento: 'treinamento',
  treinamentos: 'treinamentos',
  obrigatorio: 'obrigatório',
  obrigatoria: 'obrigatória',
  obrigatorios: 'obrigatórios',
  obrigatorias: 'obrigatórias',
  necesario: 'necessário',
  necessario: 'necessário',
  necessaria: 'necessária',
  necessarios: 'necessários',
  necessarias: 'necessárias',
  especifico: 'específico',
  especifica: 'específica',
  especificos: 'específicos',
  especificas: 'específicas',
  caracteristica: 'característica',
  caracteristicas: 'características',
  infraestrutura: 'infraestrutura',
  interface: 'interface',
  interfaces: 'interfaces',
  arquitetura: 'arquitetura',
  arquiteturas: 'arquiteturas',
  plataforma: 'plataforma',
  plataformas: 'plataformas',
  desempenho: 'desempenho',
  performance: 'performance',
  metricas: 'métricas',
  metrica: 'métrica',
  entrega: 'entrega',
  entregas: 'entregas',
  funcionalidade: 'funcionalidade',
  funcionalidades: 'funcionalidades',
  recurso: 'recurso',
  recursos: 'recursos',
  processo: 'processo',
  processos: 'processos',
  requisito: 'requisito',
  requisitos: 'requisitos',

  // ── ADVÉRBIOS / EXPRESSÕES ─────────────────────────────────────────────────
  nessa: 'nessa',
  neste: 'neste',
  nesta: 'nesta',
  proposto: 'proposto',
};

/**
 * Preserva a capitalização da palavra original ao aplicar a correção.
 * Ex: "Comecar" → "Começar", "COMECAR" → "COMEÇAR", "comecar" → "começar"
 */
function matchCase(original: string, corrected: string): string {
  if (original === original.toUpperCase()) return corrected.toUpperCase();
  if (original[0] === original[0].toUpperCase()) {
    return corrected.charAt(0).toUpperCase() + corrected.slice(1);
  }
  return corrected;
}

/**
 * Aplica o autocorrigir em um texto completo.
 * Substitui apenas palavras inteiras (word boundary), preservando pontuação.
 */
export function autocorrectPtBr(text: string): string {
  if (!text.trim()) return text;

  // Divide o texto mantendo os separadores (espaços, pontuação, quebras de linha)
  return text.replace(/[A-Za-zÀ-ÿ]+/g, (word) => {
    const lower = word.toLowerCase();
    // Remove acentos da palavra capturada para comparar com o dicionário
    const normalized = lower.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    if (DICT[normalized]) {
      return matchCase(word, DICT[normalized]);
    }
    return word;
  });
}
